### ISSUE TITLE
"active" keys in show_navtabs and navbar are in collision

### ISSUE THREAD

**Issue by novakboskov** [UKS-2015/porter#36]
- Problem

Inheritance shows its anger.

Our `templates/repository/list.html`, `templates/issue/list.html`, 'templates/milestone/list.html', 'templates/member/list.html' are extend `templates/project/base.html` which further inherits `templates/general/base.html`.

 Latter declares `templates/common/navbar.html` template in its body. That template use "active" key.
 Our templates from the beginning all declare `core/templates/show_navtabs.html` which also use an    "active" key.

Those two keys are not the same thing. First one is used for highlighting active navbar while second instructs navtab.

At the very end we have a situation where you put "active" key in `show_navtabs` like so:
`{% show_navtabs active=" issues" project_title=project_title user=user %}`
and you activate "Issues" navbar's tab instead of homonymous tab from navtab (since both the navbar and navtab have "issues" as a valid id).
- Proposed solution

More appropriate solution from the my point of view is to rename navtab's "active" key to "active_tab" since it have different meaning from navbar's "active".
- How it's partially worked until now?

Navbar have following ids declared: `dashboard, projects, issues` while navtab have: `overview, repositories, issues, milestones, members`.
"issues" is only key in intersection of these two sets, so it is the only point where this sort of inheritance shows its nature.

**Comment by lazer-nikolic** [comment]
We were completely aware that this might cause an issue, but the problem isn't what you thought. This isn't an inheritance issue and it never was; sidebar and navbar are rendered independently. 
The real problem was in the javascript function that was written instead of adding classes in templates with if statement. See example below:
`<li {% if active=='issues' %} class="active" {% endif %}><a href="{% url 'user_issues' %}" id="issues">Issues</a></li>`

Pros: no javascript and ids
Cons: more code

Each template includes a javascript function that scans the whole page looking for id, instead of limiting itself to its template. The function is included, not inherited.
It might have been better if there was no javascript involved at all, and now jquery was also introduced to fix a problem that plain old javascript easily could.

**Comment by novakboskov** [comment]
From the design perspective.
I'm watching code after c3b1e84a848996e0d2f7b1a07989dcc2fb4f61de:
You extends `templates/issue/list.html` from `template/project/base.html` which extends `templates/general/base.html`. So you have:

`general/base ---> project/base ---> issue`
- `project/base` declare name "active" and use it through `tempates/common/navbar.html`
- `templates/issue/list.html` also declare name "active" and use it through `templates/show_navtabs.html`.

Your `templates/issue/list.html` ends up with everything from the chain `general/base ---> project/base ---> issue`, it means with two names "active" with different meaning.
If you promote two different names for two different things, your'e done.

You are absolutely right about rendering order inside templates but it is technical side of coin, I'm talking about design.
You're also right on JS, I don't like it too, my proposed solution is more like a showcase of different name - different thing approach.
JQuery is more declarative than plain old JS and that's the only reason why it's here.

This is just my opinion (with some supporting material), so please don't be offended. :)
